# Generated by Django 2.2.2 on 2019-06-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190616_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Touroku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=30)),
                ('breakfast', models.BooleanField()),
                ('lunch', models.BooleanField()),
                ('dinner', models.BooleanField()),
                ('eatout', models.BooleanField()),
                ('drinking', models.BooleanField()),
                ('workout', models.BooleanField()),
                ('stretch', models.BooleanField()),
                ('studying', models.BooleanField()),
                ('awaketime', models.TimeField()),
                ('asleeptime', models.TimeField()),
                ('kenkobody', models.CharField(max_length=30)),
                ('workcond', models.CharField(max_length=30)),
            ],
        ),
    ]
