# Generated by Django 2.2.2 on 2019-06-16 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_touroku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='touroku',
            old_name='breakfast',
            new_name='bf',
        ),
    ]
