# Generated by Django 2.2.2 on 2019-06-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190616_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touroku',
            name='asleeptime',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='touroku',
            name='awaketime',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='touroku',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
