# Generated by Django 2.2.2 on 2019-06-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190616_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touroku',
            name='asleeptime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='touroku',
            name='awaketime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='touroku',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
